name: Python CI

on:
  push:

env:
  APP_NAME: GitHub-Actions-Practice
  ENVIRONMENT: testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Show configuration
        run: |
          echo "Application: $APP_NAME"
          echo "Environment: $ENVIRONMENT"

      - name: Test GitHub Secret
        run: echo "Secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Run tests
        run: pytest
